{"uuid": "92b94693-5c25-4639-b7cb-2663409789e5", "children": ["22fa59af-b3d6-4a17-be1b-6b2b834ba3ec"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=115.0.5790.111)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00D1A813+48355]\n\t(No symbol) [0x00CAC4B1]\n\t(No symbol) [0x00BB5358]\n\t(No symbol) [0x00BB1B33]\n\t(No symbol) [0x00BA8CA5]\n\t(No symbol) [0x00BA9D0A]\n\t(No symbol) [0x00BA9003]\n\t(No symbol) [0x00BA8355]\n\t(No symbol) [0x00BA82EC]\n\t(No symbol) [0x00BA6F26]\n\t(No symbol) [0x00BA7688]\n\t(No symbol) [0x00BB6B52]\n\t(No symbol) [0x00C0CF01]\n\t(No symbol) [0x00BFA73C]\n\t(No symbol) [0x00C0C922]\n\t(No symbol) [0x00BFA536]\n\t(No symbol) [0x00BD82DC]\n\t(No symbol) [0x00BD93DD]\n\tGetHandleVerifier [0x00F7AABD+2539405]\n\tGetHandleVerifier [0x00FBA78F+2800735]\n\tGetHandleVerifier [0x00FB456C+2775612]\n\tGetHandleVerifier [0x00DA51E0+616112]\n\t(No symbol) [0x00CB5F8C]\n\t(No symbol) [0x00CB2328]\n\t(No symbol) [0x00CB240B]\n\t(No symbol) [0x00CA4FF7]\n\tBaseThreadInitThunk [0x75CA7D59+25]\n\tRtlInitializeExceptionChain [0x77EBB79B+107]\n\tRtlClearBits [0x77EBB71F+191]\n\n", "trace": "  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\sudhir\\software testing\\Automation Pytest Selenium Practice\\3 Aug PageObject Model\\testCases\\conftest.py\", line 38, in setup\n    driver.get(\"https://automation.credence.in/shop\")\n  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\rthoo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691418958433, "stop": 1691418960273}], "start": 1691418958433, "stop": 1691418962363}